# Verify lightning like Minecraft or do a less precise one by checking the upper block (which may cause the block to be black)
preciseLightning: true

# The maximum distance (in chunks) a player can tick custom blocks
viewDistance: 6