name: Krimson
version: ${version}
main: ovh.paulem.krimson.Krimson
api-version: '1.19'
load: STARTUP
authors: [ Paulem ]
description: A lib to create custom blocks in a Spigot environment.
website: paulem.ovh

commands:
  display:
    description: Your description
    usage: /<command>