name: Krimson
version: ${version}
main: net.paulem.krimsontest.TestPlugin
api-version: '1.19'
load: STARTUP
authors: [ Paulem ]
description: A lib to create custom blocks in a Spigot environment.
website: paulem.net

softdepend:
  - ViaVersion

commands:
  krimson:
    description: General Krimson command
    usage: /krimson
  ui:
    description: Test UI elements
    usage: /ui <type> [action]
  stand:
    description: Spawn and animate the model rig.
    usage: /stand <spawn|remove|removeall|play|stop|pause|speed|scale|list|info>
  bdengine:
    description: Spawn and animate BDEngine models.
    usage: /bdengine <models|spawn|play|loop|stop|remove|removeall|list|info>
  custommob:
    description: Spawn and animate custom mobs.
    usage: /custommob <types|spawn|anim|remove|removeall|list|info>
